inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - grape_logging.gemspec
  NewCops: enable
  TargetRubyVersion: 3.1

Layout/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
